# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Configure CSS for overflow
        run: |
          # Create or modify CSS to handle overflow
          cat > style.css << 'EOF'
          * {
            box-sizing: border-box;
          }
          
          body {
            margin: 0;
            padding: 20px;
            overflow-x: hidden;
            max-width: 100vw;
          }
          
          .container {
            width: 100%;
            max-width: 1200px;
            margin: 0 auto;
            overflow: hidden;
          }
          
          img, video, iframe {
            max-width: 100%;
            height: auto;
          }
          
          pre, code {
            overflow-x: auto;
            white-space: pre-wrap;
            word-wrap: break-word;
          }
          
          table {
            width: 100%;
            overflow-x: auto;
            display: block;
          }
          EOF
          
          # Add CSS link to HTML files if they exist
          if [ -f "index.html" ]; then
            sed -i 's|</head>|<link rel="stylesheet" href="style.css"></head>|' index.html
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: '.'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
